# Generated by Django 3.0.4 on 2020-03-30 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=250)),
                ('Location', models.CharField(max_length=250)),
                ('company', models.CharField(max_length=250)),
                ('Salary', models.CharField(max_length=250)),
                ('Job_Date', models.CharField(max_length=250)),
                ('Description', models.CharField(max_length=1500)),
            ],
        ),
    ]
